#facebook: "https://facebook.com/example"
twitter: "https://twitter.com/swissbib"
email: "swissbib-ub@unibas.ch"
name: "project swissbib"
location: Basel
#phone: (999) 999-9999
#hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"
