baseURL: http://swissbib.hithub.io                  # Hosting location.
languageCode: de-ch                           # Locale
title: swissbib data blog                       # Name of the website
theme: hia                                    # Name of the theme
enableEmoji: true                             # Enable Emoticons

publishDir: docs
relativeURLs: false

