color: "#50bf9e"


copyright: ""
footer:
#  - title:
#    content:
  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Us
    contact: true
style: green
logo: image/logo.png
logo_small: image/logo.png
about_us:
recent_posts:
  enable: true
