color: "#50bf9e"


copyright: "Copyright &copy; 2020 Acme Corporation. All Rights Reserved."
footer:
  - title: About
    content: content about footer
  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Us
    contact: true
style: green
logo: image/logo.png
logo_small: image/logo.png
about_us: here about us
recent_posts:
  enable: true
